genomes_tsv: "genomes.tsv"

working_dir: "workingDir"
postdir: "post_genespace"

gff_dir: "gff"
protein_dir: "protein"
cds_dir: "cds"
chr_dict_dir: "chr_dict"

ext:
  gff: "gff3"
  pep: "pep"

orthofinder_bin: "orthofinder"
macse_bin: "macse"
iqtree_bin: "iqtree3"
alerax_bin: "alerax"

force_orthofinder: false
run_external_orthofinder: false
orthofinder_dir_override: ""
orthofinder_analysis_threads: 2

genespace:
  rawOrthofinderDir: ""
  blkSize: 5
  orthofinder_in_blk: true

alerax:
  species_tree: "snakemake/species_tree.nwk"
  rec_model: "UndatedDL"
  model_parametrization: "PER-SPECIES"
  gene_tree_samples: 100

array_size: 10000

containers:
  genespace: "ghcr.io/bhban/genespace:1.1"
  macse: "ghcr.io/bhban/macse:1.0"
  iqtree: "ghcr.io/bhban/iqtree:1.0"
  alerax: "ghcr.io/bhban/alerax:1.0"

sif_paths:
  genespace: "/exports/cmvm/eddie/eb/groups/macqueen_lab/brianna/containers/genespace_1.0.sif"
  macse: "/exports/cmvm/eddie/eb/groups/macqueen_lab/brianna/containers/macse_1.0.sif"
  iqtree: "/exports/cmvm/eddie/eb/groups/macqueen_lab/brianna/containers/iqtree_1.0.sif"
  alerax: "/exports/cmvm/eddie/eb/groups/macqueen_lab/brianna/containers/alerax_1.0.sif"
